In [1]:
import numpy as np
import pandas as pd 
import tensorflow as tf 
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv("Insurance.csv")

In [3]:
df.head()

age  affordibility  have_insurance
0   22              1               0
1   25              0               0
2   47              1               1
3   52              0               0
4   46              1               1

In [4]:
df.shape

(28, 3)

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.have_insurance,test_size=.2,random_state=25)

In [6]:
len(x_train)

22

In [7]:
x_train_scaled=x_train.copy()
x_train_scaled['age']=x_train_scaled['age']/100

x_test_scaled=x_test.copy()
x_test_scaled['age']=x_test_scaled['age']/100

In [8]:
x_train_scaled.head()

age  affordibility
0   0.22              1
13  0.29              0
6   0.55              0
17  0.58              1
24  0.50              1

## Creating model 

In [9]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy'])
model.fit(x_train_scaled,y_train,epochs=200)

Epoch 1/200
1/1 [==============================] - 0s 419ms/step - loss: 0.6347 - accuracy: 0.5909
Epoch 2/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6345 - accuracy: 0.5909
Epoch 3/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6342 - accuracy: 0.5909
Epoch 4/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6340 - accuracy: 0.5909
Epoch 5/200
1/1 [==============================] - 0s 998us/step - loss: 0.6338 - accuracy: 0.5909
Epoch 6/200
1/1 [==============================] - 0s 963us/step - loss: 0.6336 - accuracy: 0.5909
Epoch 7/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6334 - accuracy: 0.5909
Epoch 8/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6332 - accuracy: 0.5909
Epoch 9/200
1/1 [==============================] - 0s 4ms/step - loss: 0.6330 - accuracy: 0.5909
Epoch 10/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6328 - accuracy: 0.5909
Epoch 11/200
1/1 [=====

1/1 [==============================] - 0s 3ms/step - loss: 0.6206 - accuracy: 0.5909
Epoch 85/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6204 - accuracy: 0.5909
Epoch 86/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6203 - accuracy: 0.5909
Epoch 87/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6202 - accuracy: 0.5909
Epoch 88/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6200 - accuracy: 0.5909
Epoch 89/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6199 - accuracy: 0.5909
Epoch 90/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6198 - accuracy: 0.5909
Epoch 91/200
1/1 [==============================] - 0s 997us/step - loss: 0.6197 - accuracy: 0.5909
Epoch 92/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6195 - accuracy: 0.5909
Epoch 93/200
1/1 [==============================] - 0s 997us/step - loss: 0.6194 - accuracy: 0.5909
Epoch 94/200
1/1 [===========

1/1 [==============================] - 0s 2ms/step - loss: 0.6123 - accuracy: 0.5909
Epoch 167/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6122 - accuracy: 0.5909
Epoch 168/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6121 - accuracy: 0.5909
Epoch 169/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6121 - accuracy: 0.5909
Epoch 170/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6120 - accuracy: 0.5909
Epoch 171/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6119 - accuracy: 0.5909
Epoch 172/200
1/1 [==============================] - 0s 3ms/step - loss: 0.6118 - accuracy: 0.5909
Epoch 173/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6118 - accuracy: 0.5909
Epoch 174/200
1/1 [==============================] - 0s 997us/step - loss: 0.6117 - accuracy: 0.5909
Epoch 175/200
1/1 [==============================] - 0s 2ms/step - loss: 0.6116 - accuracy: 0.5909
Epoch 176/200
1/1 [===

In [10]:
model.evaluate(x_test_scaled,y_test)

1/1 [==============================] - 0s 113ms/step - loss: 0.6677 - accuracy: 0.5000


[0.6676662564277649, 0.5]

In [11]:
x_test_scaled

age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

In [12]:
model.predict(x_test_scaled)

array([[0.7502942 ],
       [0.69726974],
       [0.5154766 ],
       [0.7162637 ],
       [0.7537135 ],
       [0.77356017]], dtype=float32)

In [13]:
coef,intercept=model.get_weights()
coef,intercept

(array([[0.91673   ],
        [0.84574246]], dtype=float32),
 array([-0.17642361], dtype=float32))

## Check in python code

In [14]:
import math
def sigmoid(x):
    return 1/(1+math.exp(-x))
sigmoid(18)

0.9999999847700205

In [15]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [16]:
prediction_function(25,1)

0.9999999999429772

In [17]:
prediction_function(56,1)

1.0

In [18]:
def log_loss(y_real,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_real*np.log(y_predicted_new)+(1-y_real)*np.log(1-y_predicted_new)) 

In [25]:
def sigmoid_numpy(x):
    return (1/(1+np.exp(-x)))
sigmoid_numpy= np.vectorize(sigmoid_numpy)
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [30]:
def grediant_descent(age, affordibility,y_real,epochs):
    w1=w2=1 #this is random
    bias=0 # this is random
    rate=0.5 # this is radom
    n= len(age)
    for i  in range(epochs):
        weighted_sum = w1*age + w2*affordibility +bias
        y_predicted = sigmoid_numpy(weighted_sum)
        loss= log_loss(y_real,y_predicted)
        w1d= (1/n)*np.dot(np.transpose(age),(y_predicted-y_real))
        w2d= (1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_real))
        bias_d=np.mean(y_predicted-y_real)
        w1=w1-rate*w1d
        w2=w2-rate*w2d
        print(f"Epoch{epochs}, w1{w1}, w2{w2}, Bias{bias}, Loss{loss}")
    return w1,w2,bias

In [42]:
grediant_descent(x_train_scaled['age'], x_train_scaled['affordibility'],y_train,250)

Epoch250, w10.9907935440408127, w20.9718534166129719, Bias0, Loss0.6346629803353081
Epoch250, w10.9822988457688695, w20.9453180752475226, Bias0, Loss0.6329607413873718
Epoch250, w10.9744842020227098, w20.9203261765063466, Bias0, Loss0.6314547683088135
Epoch250, w10.967317663085986, w20.8968090220823797, Bias0, Loss0.6301252485169614
Epoch250, w10.9607672897186681, w20.8746976242560986, Bias0, Loss0.6289537979728407
Epoch250, w10.9548013819425827, w20.8539232494460756, Bias0, Loss0.6279234698764314
Epoch250, w10.9493886790741844, w20.8344178946729324, Bias0, Loss0.6270187364561268
Epoch250, w10.9444985313445382, w20.8161146977680993, Bias0, Loss0.6262254490799323
Epoch250, w10.9401010441175228, w20.7989482837140448, Bias0, Loss0.6255307816021958
Epoch250, w10.9361671962217425, w20.7828550506667349, Bias0, Loss0.6249231614061426
Epoch250, w10.9326689342656443, w20.767773400023627, Bias0, Loss0.6243921920673453
Epoch250, w10.9295792450287672, w20.7536439154092989, Bias0, Loss0.62392857099

Epoch250, w11.1013126029992486, w20.4770299384593413, Bias0, Loss0.6199918707910281
Epoch250, w11.1023148170497006, w20.47658085566540087, Bias0, Loss0.6199894333587752
Epoch250, w11.1033101235331102, w20.4761348997456427, Bias0, Loss0.6199870294692769
Epoch250, w11.1042985703154005, w20.4756920477436377, Bias0, Loss0.6199846586577661
Epoch250, w11.1052802049498884, w20.4752522769361616, Bias0, Loss0.6199823204659783
Epoch250, w11.106255074677374, w20.4748155648264445, Bias0, Loss0.6199800144420591
Epoch250, w11.1072232264263961, w20.47438188913784846, Bias0, Loss0.6199777401404728
Epoch250, w11.1081847068136421, w20.47395122780794263, Bias0, Loss0.6199754971219137
Epoch250, w11.1091395621444982, w20.4735235589829453, Bias0, Loss0.6199732849532172
Epoch250, w11.1100878384137287, w20.47309886101250637, Bias0, Loss0.6199711032072733
Epoch250, w11.111029581306273, w20.4726771124448049, Bias0, Loss0.6199689514629402
Epoch250, w11.1119648361981485, w20.4722582920219386, Bias0, Loss0.6199668

(1.171380035939893, 0.44568830851224284, 0)

In [43]:
coef,intercept

(array([[0.91673   ],
        [0.84574246]], dtype=float32),
 array([-0.17642361], dtype=float32))

In [58]:
class my_nn:
    def __init__(self):
        self.w1=1
        self.w2=1
        self.bias=0
    def fit(self,x,y,epochs):
        self.w1, self.w2, self.bias =self.grediant_descent(x['age'],x['affordibility'],y,epochs)
       
    def predict(self,x_test):
            weighted_sum = self.w1*x_test['age'] + self.w2*x_test['affordibility'] + self.bias
            return sigmoid_numpy(weighted_sum)
    def grediant_descent(self,age, affordibility,y_real,epochs):
        w1=w2=1 #this is random
        bias=0 # this is random
        rate=0.5 # this is radom
        n= len(age)
        for i  in range(epochs):
            weighted_sum = w1*age + w2*affordibility +bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss= log_loss(y_real,y_predicted)
            w1d= (1/n)*np.dot(np.transpose(age),(y_predicted-y_real))
            w2d= (1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_real))
            bias_d=np.mean(y_predicted-y_real)
            w1=w1-rate*w1d
            w2=w2-rate*w2d
            print(f"Epoch{epochs}, w1{w1}, w2{w2}, Bias{bias}, Loss{loss}")
        return w1,w2,bias

In [59]:
obj=my_nn()
obj.fit(x_train_scaled,y_train,epochs=5)

Epoch5, w10.9907935440408127, w20.9718534166129719, Bias0, Loss0.6346629803353081
Epoch5, w10.9822988457688695, w20.9453180752475226, Bias0, Loss0.6329607413873718
Epoch5, w10.9744842020227098, w20.9203261765063466, Bias0, Loss0.6314547683088135
Epoch5, w10.967317663085986, w20.8968090220823797, Bias0, Loss0.6301252485169614
Epoch5, w10.9607672897186681, w20.8746976242560986, Bias0, Loss0.6289537979728407


In [60]:
obj.predict(x_test_scaled)

array([0.79022103, 0.74032064, 0.56212715, 0.7583606 , 0.79338863,
       0.81164975])

In [61]:
model.predict(x_test_scaled)

array([[0.7502942 ],
       [0.69726974],
       [0.5154766 ],
       [0.7162637 ],
       [0.7537135 ],
       [0.77356017]], dtype=float32)