## How work loss and cost function

In [1]:
import numpy as np
y_predicted=np.array([1,1,0,0,1])
y_real=np.array([0.30,0.7,1,0,0.5])

## Mean_absolute_error

In [2]:
def mae(y_real,y_predicted):
    total_error=0
    for yr,yp in zip(y_real,y_predicted):
        error=abs(yr-yp)
        total_error += error
    print("Total Error",total_error)
    mae=total_error/len(y_real)
    print("MSE",mae)
    return mae    
    

In [3]:
mae(y_real,y_predicted)

Total Error 2.5
MSE 0.5


0.5

## Numpy provided function which can calculate error in just one line

In [4]:
np.sum(abs(y_real-y_predicted))

2.5

In [5]:
np.mean(abs(y_real-y_predicted))

0.5

## Log_loss

In [6]:
np.log([0.0000000000000000000001])

array([-50.65687205])

In [7]:
epsilon=1e-15

In [8]:
y_predicted_new=[max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [9]:
y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [10]:
y_predicted_new=np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [11]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [12]:
-np.mean(y_real*np.log(y_predicted_new)+(1-y_real)*np.log(1-y_predicted_new))

17.2696280766844

## Define function for log loss

In [13]:
def log_loss(y_real,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_real*np.log(y_predicted_new)+(1-y_real)*np.log(1-y_predicted_new)) 

In [14]:
log_loss(y_real,y_predicted)

17.2696280766844

## Mean_squared_error

In [15]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [16]:
mse(y_real, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

### By using numpy

In [19]:
np.mean(np.square(y_real-y_predicted))

0.366