In [2]:
import numpy as np

In [6]:
arr=np.array([[4,6,3,8,9],[4,7,3,8,7]])

In [7]:
arr

array([[4, 6, 3, 8, 9],
       [4, 7, 3, 8, 7]])

In [8]:
lst=[[4,6,3,8,9],[4,7,3,8,7],[5,9,4,7,3]]

In [10]:
arr=np.array(lst)
arr

array([[4, 6, 3, 8, 9],
       [4, 7, 3, 8, 7],
       [5, 9, 4, 7, 3]])

In [13]:
arr[2][1]

9

In [20]:
ar=np.array([4,64,3,8,9] ,np.int8)

In [21]:
ar

array([ 4, 64,  3,  8,  9], dtype=int8)

In [22]:
arr

array([[4, 6, 3, 8, 9],
       [4, 7, 3, 8, 7],
       [5, 9, 4, 7, 3]])

In [23]:
arr.shape

(3, 5)

In [32]:
arr=np.array([[4,6,3,8,9],[4,7,3,8,7],[5,9,4,7,3]])
arr.reshape(5,3)

array([[4, 6, 3],
       [8, 9, 4],
       [7, 3, 8],
       [7, 5, 9],
       [4, 7, 3]])

In [34]:
arr.T

array([[4, 4, 5],
       [6, 7, 9],
       [3, 3, 4],
       [8, 8, 7],
       [9, 7, 3]])

In [43]:
arr1=np.array([[4,6,3,8,9],[4,7,3,8,7]])
arr2=np.array([[3,6,3,8,5],[6,2,1,5,7]])
arr1

array([[4, 6, 3, 8, 9],
       [4, 7, 3, 8, 7]])

In [39]:
arr2

array([[3, 6, 3, 8, 5],
       [6, 2, 1, 5, 7]])

In [42]:
arrr=arr1+arr2
arrr

array([[ 7, 12,  6, 16, 14],
       [10,  9,  4, 13, 14]])